model:
  master_agent:
    api_provider: bedrock 
    model_id: us.anthropic.claude-3-7-sonnet-20250219-v1:0
    params:
      max_tokens: 4096
      temperature: 0

  text_agent:
    api_provider: bedrock 
    model_id: us.anthropic.claude-3-7-sonnet-20250219-v1:0
    params:
      max_tokens: 4096
      temperature: 0

  image_agent:
    api_provider: bedrock 
    model_id: us.anthropic.claude-3-7-sonnet-20250219-v1:0
    params:
      max_tokens: 4096
      temperature: 0

  video_agent:
    api_provider: openai
    model_id: Isotr0py/LLaVA-Video-7B-Qwen2-hf
    base_url: http://localhost:8000/v1
    max_image_input: 6
    max_frames_num: 30
    image_size: [336, 336]
    params:
      max_tokens: 4096
      temperature: 0

  audio_agent:
    api_provider: openai
    model_id: Qwen/Qwen2.5-Omni-7B
    base_url: http://localhost:8000/v1
    params:
      max_tokens: 4096
      temperature: 0

agents:
  supported: ["text", "image", "video", "audio"]
  names: ["text_agent", "image_agent", "video_agent", "audio_agent"]

system:
  retry_times: 2

