model:
  master_agent: ../configs/model_configs/gemini-2.0-flash.yaml
  text_agent: ../configs/model_configs/gemini-2.0-flash.yaml
  video_agent: ../configs/model_configs/gemini-2.0-flash.yaml
  audio_agent: ../configs/model_configs/gemini-2.0-flash.yaml

agents:
  supported: ["text", "video", "audio"]
  names: ["text_agent", "video_agent", "audio_agent"]

system:
  retry_times: 3

